[package]
name = "rust_dl"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15"
ndarray-csv = "0.5"
csv = "1.1"
uuid = { version = "1", features = ["v4"] }
indicatif = "0.17"